[package]
name = "ark-mnt4-298"
version = "0.2.0"
authors = [ "arkworks contributors" ]
description = "The MNT4-298 pairing-friendly elliptic curve"
homepage = "https://arkworks.rs"
repository = "https://github.com/arkworks-rs/algebra"
documentation = "https://docs.rs/ark-mnt4-298/"
keywords = ["cryptography", "finite-fields" ]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
ark-ff = { path="../../algebra/ff", version="^0.2.0", default-features = false }
ark-ec = { path="../../algebra/ec", version="^0.2.0", default-features = false }
ark-r1cs-std = { path="../../r1cs-std", version="^0.2.0", default-features = false, optional = true }
ark-std = { path = "../../utils",  version="^0.2.0", default-features = false }

[dev-dependencies]
ark-relations = { version="^0.2.0", path = "../../snark/relations", default-features = false }
ark-serialize = { version="^0.2.0", path = "../../algebra/serialize", default-features = false }
ark-algebra-test-templates = { version="^0.2.0", path = "../../algebra/test-templates", default-features = false }
ark-curve-constraint-tests = { version="^0.2.0", path = "../curve-constraint-tests", default-features = false }

[features]
default = [ "curve" ]
std = [ "ark-std/std", "ark-ff/std", "ark-ec/std" ]

curve = [ "scalar_field", "base_field" ]
scalar_field = []
base_field = []
r1cs = [ "base_field", "ark-r1cs-std" ]
